name: Tomcat Server Deployment

on:
  push:
    branches:
      - testing
  workflow_dispatch:
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install java 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
      - name: 'clone code' 
        uses: actions/checkout@v3

      - name: permissions
        run: chmod +x ./mvnw

      - name: build using maven
        run: ./mvnw package
      
      - name: verify if build was successful
        run: ls -l target/*.war 

      - name: copy something
        uses: garygrossgarten/github-action-scp@release
        with:
          local: 'target/apiservice-0.0.1-SNAPSHOT.war'
          remote:  'C:\Users\hasan\Desktop'
          host: 20.120.93.141
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}



