name: Tomcat Server Deployment

on:
  push:
    branches:
      - testing
  workflow_dispatch:
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install java 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
      - uses: actions/checkout@v3

      - run: chmod +x ./mvnw

      - name: build using maven
        run: ./mvnw package