name: Tomcat Server Deployment
env:
  RUN_NUMBER: ${{ github.run_number }}
on:
  push:
    branches:
      - testing
  workflow_dispatch:

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install java 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 

      - name: 'clone code' 
        uses: actions/checkout@v3

      - name: permissions
        run: chmod +x ./mvnw

      - name: modify pom.xml with version
        run: sed -i "s/VERSION_NUMBER/${{ env.RUN_NUMBER }}" pom.xml
      - name: build using maven
        run: ./mvnw package
      
      - name: verify if build was successful
        run: ls -l target/*.war 

      - name: copy something
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: './target/*.war'
          remote:  'C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\'
          host: 20.120.93.141
          user: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          pre_upload: echo "Uploading before upload"
          post_upload: Powershell.exe 'ls -l C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\*.war'