name: Tomcat Server Deployment

on:
  push:
    branches:
      - testing
  workflow_dispatch:
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install java 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 
          cache: 'maven'
      - name: verify java version
        run: java --version
      - name: build using maven
        run: ./mvnw package
      # - name: verify if built successfully
      #   uses: 
     # - name: deploy build to tomcat
      #  uses:

